theme: osuny
_merge: deep
params:
  summary:
    position: hero
  search:
    active: true
  posts:
    index:
      layout: grid
  debug:
     productionUrl: "https://ressources.rebootcommunication.org/"